#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code with black
"
}

DIRS_TO_CHECK=("src" "tests" "scripts")

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Sort imports
        isort -v --overwrite-in-place .
        # Code formatting
        black .
    fi
fi
