#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters.
"
}

EC_EXCLUDE="(__pycache__|.git|.coverage|coverage.xml|.*\.egg-info|.mypy_cache|.tif|.tiff|.npy|.ipynb|*.json)"

DIRS_TO_CHECK=("src" "tests" "scripts")

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Disabled ec, seeing errors on CI I can't reproduce
        # README.md:
        # Wrong line endings or new final newline
        # examples/collection.json:
        # Wrong line endings or new final newline

        # Text formatting
        # echo ["running ec"]
        # ec --exclude "$EC_EXCLUDE"
        # Code formatting
        echo ["running black"]
        black --check .
        # Lint
        echo ["running flake8"]
        flake8 ${DIRS_TO_CHECK[@]}
        # Type checking
        echo ["running mypy"]
        mypy src
    fi
fi
