#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Run format
	echo ["running format"]
	./scripts/format
	
	# Check code formatting, lint, and type checking
	echo ["running scripts/lint"]
        ./scripts/lint
	
	# Codespell
	echo ["run codespell"]
        ./scripts/codespell

        codespell -I .codespellignore -f \
            scripts/* \
            *.py ./**/*.py \
            *.md \
            docs/*.rst docs/**/*.rst \
            docs/*.ipynb docs/**/*.ipynb

        coverage run --source=${COVERAGE_DIRS} -m unittest discover tests/
        coverage xml
        pytest tests
    fi
fi
